name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: http request
      env:
        secret: ${{ secrets.DeploySecret }}
      run: curl "https://deploy.walduni.de?secret=${secret}"
